### ISSUE TITLE
add new method to show all vid.cantidad group by bodega

### ISSUE THREAD

**Issue by Japoivvb** [SergiGuasp/Viticultura#4]
1. after current showAllCampos() create a new method showCantidadVidByBodega()

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by SergiGuasp** [comment]
![image](https://github.com/SergiGuasp/Viticultura/assets/135022749/3d4868b8-3fcb-48b4-9933-65a0542304cf)
![image](https://github.com/SergiGuasp/Viticultura/assets/135022749/7414177d-9e3d-41b0-b5ee-e79d6087d95b)
![image](https://github.com/SergiGuasp/Viticultura/assets/135022749/4495d8a8-0781-4034-8b5b-c1910bfee83d)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
