### ISSUE TITLE
add new field precio to vid model

### ISSUE THREAD

**Issue by Japoivvb** [SergiGuasp/Viticultura#5]
1. add double price attribute to vid model and verify everything is working again

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by SergiGuasp** [comment]
![image](https://github.com/SergiGuasp/Viticultura/assets/135022749/3d493ad7-70c4-4295-9a29-a43f731e2c8c)
![image](https://github.com/SergiGuasp/Viticultura/assets/135022749/aa025cb8-2e7d-47e6-a715-364483b7b906)

**Comment by SergiGuasp** [comment]
Me he dado cuenta de que los datos no los estaba añadiendo a traves de las instrucciones de entrada, en este commit lo he echo bien:
https://github.com/SergiGuasp/Viticultura/commit/7070f4cd4222f8f9f1df45aa44633a31446aa852

**Comment by SergiGuasp** [comment]
![image](https://github.com/SergiGuasp/Viticultura/assets/135022749/bfc55c81-6fd3-44f4-b48b-fbe370bdb502)
He cambiado las instrucciones de entrada, he modificado el constructor de Vid añadiendo price y he modificado el metodo añadiendo el price tambien.

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
